// 1.用户信息
export const USER_INFO = 'USER_INFO';
//购物车
export const ADD_TO_CART = 'ADD_TO_CART';
export const ADD_GOODS = 'ADD_GOODS';

export const SINGLE_SELECT_GOODS = 'SINGLE_SELECT_GOODS';
export const ALL_SELECT_GOODS = 'ALL_SELECT_GOODS';
export const DELETE_SELECT_GOODS = 'DELETE_SELECT_GOODS';

export const CHANGE_ADDRESS = 'CHANGE_ADDRESS';

export const DEFAULT_ADDRESS = 'DEFAULT_ADDRESS';

export const ADD_ADDRESS = 'ADD_ADDRESS';

export const USER_COUPON = 'USER_COUPON';

export const SELETE_COUPON = 'SELETE_COUPON';

export const USECOUPONTEXT = 'USECOUPONTEXT';

export const ALL_CART = 'ALL_CART';

export const COUPON_TOTAL = 'COUPON_TOTAL';

export const FREIGHT = 'FREIGHT';

export const GETMEMBERINFO = 'GETMEMBERINFO';

export const ISRENDORDER = 'ISRENDORDER';

export const ISPOPPASS = 'ISPOPPASS'

export const SENDEXPESSADDRESS = 'SENDEXPESSADDRESS'